### ISSUE TITLE
PyDrive err

### ISSUE THREAD

**Issue by wangzhijin** [gsuitedevs/PyDrive#130]
Hi there,

I am having issues authenticated via PyDrive.

When I execute my basic code, api_practice.py file:
```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
gauth = GoogleAuth()
gauth.CommandLineAuth()
drive = GoogleDrive(gauth)
f = drive.CreateFile({'title': 'test.txt'})
f.SetContentString('test pydrive')
f.Upload()

```
in the same path, My settings.yaml file contains:

```
client_config_backend: settings
client_config:
  client_id: 51***************f.apps.googleusercontent.com
  client_secret: Z1***************

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
```
  
and follow the output url, and grant permissions (via the web browser),
input Enter verification code,then there is a error:  
```
Traceback (most recent call last):
  File "api_practice.py", line 7, in <module>
    gauth.CommandLineAuth()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydrive\auth.py", line 125, i
n _decorated
    self.Auth(code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydrive\auth.py", line 495, i
n Auth
    self.Authenticate(code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pydrive\auth.py", line 508, i
n Authenticate
    self.credentials = self.flow.step2_exchange(code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\_helpers.py", li
ne 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\client.py", line
 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\transport.py", l
ine 282, in request
    connection_type=connection_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1
514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1
264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1
187, in _conn_request
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1
050, in connect
    raise socket_err
  File "C:\ProgramData\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1
011, in connect
    sock.connect((self.host, self.port))
TimeoutError: [WinError 10060] 接続済みの呼び出し先が一定の時間を過ぎても正しく
応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかった
ため、確立された接続は失敗しました。
```
I have tried two method to solute this problem,but Useless
 a. maybe it's a proxy problem,I tried add proxy setting into basic code→same err
 b. I tried make a new client_id and client_secret→same err

Does anyone have any ideas what is going on here?

**Comment by wangzhijin** [comment]
Storage Server seems limited by company network,
I have cleaned this problem on my private PC.
