### ISSUE TITLE
Receiving Error "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

### ISSUE THREAD

**Issue by jimbasquiat** [gsuitedevs/PyDrive#133]
Few files manage to get uploaded, then I receive the error message: `Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.`

Going to the link provided in the error , I see a basic html page with the following indications:

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

I looked up stackoverflow etc. for resolution of that error but couldnt find anything clear enough for me to fix my problem. Some SO post suggest that a 'key' param should be added to the query string, but witout explaining what that key is suppsoed to be found exactly...

i am using a setting.yaml file for the auth process. The file contains the following :

```
client_config_file: client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
```

Additionaly I want to point out that there iare always a bunch of error messages at the begining of the script (see below). They don't seem to prevent the few first entries to be uploaded, but they might prevent correct authentication. I tried to install `appengine` with `pip install googleappengine` and `pip install appengine` but it seems those are only available for python 2 (and my project is python3.6...)

```
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/vincent/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
```

**Comment by yuttai** [comment]
I encounter a similar problem: A HTTP 400 error first, and HTTP 403 when going to the link...
`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v2/files?q=%2713S7A11nmsnRXzCkSM5sR3IHCzT8_frDw%27+in+parents+and+trashed+%3D+false+and+title+%3D+%27cid_settings_prepare_trial+False+origin%5Cyuttai+adwords_optimization_39_master+301%27&alt=json&maxResults=1000 returned "Invalid query">`

I guess my HTTP 400 error is because my file name is strange, and the later HTTP 403 is just because the browser isn't authenticated to read Google Drive API URL... However, anything is no sure...

**Comment by yuttai** [comment]
The error disappear after I replace '/' in my file by '-'...
